apiVersion: v1
kind: Service
metadata:
  name: sentiment-app-service
spec:
  selector:
    app: sentiment-app
  ports:
    - name: web
      protocol: TCP
      port: 8001
      targetPort: 8001
    - name: streamlit
      protocol: TCP
      port: 8502
      targetPort: 8502
  type: NodePort
